### ISSUE TITLE
fatal : no remote found for dependency...

### ISSUE THREAD

**Issue by js-seth-h** [componentjs/component#637]
Hi.
I am getting problems
fail to install in particular computer.
but other one (in same local network, same component version) is success.
furthermore, when after "npm  install -g component" yesterday, it is working good. 
I don't know why. and how to fix it?
help me plz.

 ```console
C:\>component install lodash/lodash

  remotes:local checking local components at C:\components +0ms
  component-resolver remote not set - defaulting to remotes's defaults +4ms
  component-resolver:locals resolving local at "C:\" +4ms
  component-resolver resolving "root" +1ms
  component-resolver remaining dependencies: 1 +4ms
  component-resolver remaining semver: 0 +1ms
  component-resolver finished resolving locals +1ms
  component-resolver finished resolving dependencies (1) +1ms
  component-resolver:semver resolving semver lodash/lodash@* +1ms
  remotes:local checking folder: C:\components\lodash\lodash +2ms
  remotes:github GET "https://api.github.com/repos/lodash/lodash/tags" +3ms
  cogent options: { protocol: 'https:',
  slashes: true,
  auth:  // AUTH TOKEN REMOVE... 
  host: 'api.github.com',
  port: null,
  hostname: 'api.github.com',
  hash: null,
  search: null,
  query: null,
  pathname: '/repos/lodash/lodash/tags',
  path: '/repos/lodash/lodash/tags',
  href: 'https://api.github.com/repos/lodash/lodash/tags',
  headers:
   { 'accept-encoding': 'gzip',
     'user-agent': 'https://github.com/cojs/cogent',
     accept: 'application/json' },
  method: 'GET' } +4ms
  remotes:bitbucket GET "https://api.bitbucket.org/1.0/repositories/lodash/lodash/tags" +3s
  cogent options: { protocol: 'https:',
  slashes: true,
  auth: null,
  host: 'api.bitbucket.org',
  port: null,
  hostname: 'api.bitbucket.org',
  hash: null,
  search: null,
  query: null,
  pathname: '/1.0/repositories/lodash/lodash/tags',
  path: '/1.0/repositories/lodash/lodash/tags',
  href: 'https://api.bitbucket.org/1.0/repositories/lodash/lodash/tags',
  headers:
   { 'accept-encoding': 'gzip',
     'user-agent': 'https://github.com/cojs/cogent',
     accept: 'application/json' },
  method: 'GET' } +5ms
  component-consoler Error: no remote found for dependency "lodash/lodash".
    at Resolver.<anonymous> (C:\Users\js\AppData\Roaming\npm\node_modules\compon
ent\node_modules\component-resolver\build\semver.js:565:13)
    at Generator.invoke (C:\Users\js\AppData\Roaming\npm\node_modules\component\
node_modules\component-resolver\build\index.js:141:31)
    at Generator.invoke (C:\Users\js\AppData\Roaming\npm\node_modules\component\
node_modules\component-resolver\build\index.js:79:50)
    at next (C:\Users\js\AppData\Roaming\npm\node_modules\component\node_modules
\co\index.js:74:21)
    at C:\Users\js\AppData\Roaming\npm\node_modules\component\node_modules\co\in
dex.js:93:18
    at Gunzip.onEnd (C:\Users\js\AppData\Roaming\npm\node_modules\component\node
_modules\component-remotes\node_modules\cogent\node_modules\raw-body\index.js:14
9:7)
    at Gunzip.g (events.js:199:16)
    at Gunzip.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11) +2s

       fatal : no remote found for dependency "lodash/lodash".

  remotes:github:api used 1 +12ms
 
```

**Comment by timaschew** [comment]
works fine with component 1.1.0

```
$ component install lodash/lodash

   installed : lodash/lodash@3.8.0 in 1771ms
       install : complete

vagrant@devbox:~$ component --version
1.1.0
```

**Comment by AaronNGray** [comment]
I am getting the same issue with both VM's and Linux during times of high internet usage. I did an issue for it here https://github.com/componentjs/component/issues/634
